# Generated by Django 4.1.5 on 2023-01-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_registration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='foget_pass',
        ),
        migrations.AddField(
            model_name='adminsitting1',
            name='contact',
            field=models.IntegerField(default=0, max_length=15),
        ),
    ]
